@startuml state machine

hide empty description
[*] --> INITIAL
INITIAL: Starts the transaction
INITIAL -> WAITING
WAITING: wait until user is selected
WAITING --> SELECTED
state async <<fork>>
state isSuccess <<choice>> 

SELECTED --> async
async --> isSuccess : process
async --> AUDITED : audit
AUDITED ---> [*]
isSuccess --> SUCCESS : yes
isSuccess --> NOT_SUCCESS: no

state endAsync <<fork>>
SUCCESS --> endAsync
NOT_SUCCESS --> endAsync
endAsync --> [*]

@enduml