@startuml "Su vacuna Container"
!include <C4/C4_Container>

title Su vacnua container



Person(persona, "Persona", "Registrar el proceso de vacunacion")
System_Boundary(suVacuna, "SuVacuna", "Registrar la vacunacion contra el covid 19"){

    Container(vacunaWeb, "VacunaWEB", "Angular","Frontend para la aplicacion de su vacuna")
    Container(vacunaNode, "SuVacuna", "NodeJS","BFF para las operaciones del frontend")
    Container(vacunaGO, "SuVacunaInfo", "GO","Exponer servicios de consulta para la IPS")
    Container(vacunaSYNC, "VacunaSync", "RabbitMQ","Sincronizar lectura y escritura")

    ContainerDb(mongo, "BDLectura","mongoDB", "Base para lectura de la informacion")
    ContainerDb(oracle, "BDEscritura","Oracle", "Base para la escritura")

    Rel(vacunaWeb, vacunaNode, "Registrar todo el proceso")
    Rel(vacunaGO, mongo, "Consulta Data")
    Rel(vacunaNode, oracle, "Esribe la data")

    Rel(oracle,vacunaSYNC , "Escucha la escritura")
    Rel(vacunaSYNC, mongo, "Replico el registro en base de datos de lectura")

}
System_Ext(regix, "Regix", "Aplicación existente de la reguistraduria")
System_Ext(ips, "IPS", "Listado de las personas vacunadas")

Rel(persona, vacunaWeb, "Registra proceso")
Rel(vacunaNode, regix, "Consultar la identificacion de los usuarios")
Rel(ips, vacunaGO, "Consultar usuarios registrados")


@enduml