@startuml "AbstractFactory Pattern"


Main -> AbstractFactory: factory: AbstractFactory

alt product type A
    Main -> FactoryA: factory = new FactoryA()
end

alt product type A
    Main -> FactoryB: factory = new FactoryB()
end


Main -> Product: product: Product
Main -> AbstractFactory: factory.createProduct()

alt product type A
    FactoryA -> ProductA: factory.createProduct() :ProductA
end

alt product type B
    FactoryB -> ProductB: factory.createProduct() :ProductB
end

Main -> Main: product.doSomething()

@enduml